version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      # Prefix all commit messages with "[docker] "
      prefix: "[docker] "

  - package-ecosystem: "github-actions"
    # Workflow files are stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      # Prefix all commit messages with "[gha] "
      prefix: "[gha] "
